### ISSUE TITLE
please update this amazing addon 

### ISSUE THREAD

**Issue by nyouness** [jaruba/stremio-anime-catalogs#1]
Hello ,
can you please update this really cool addon , i already have it installed but its no longer available in stremio-addons and the provider MyAnimeList stop working and other 3 providers Kitsu , AniDB , AniList are limited , and please let us the stremio community know when u done updating it we will be soo happy to see this addon alive .
Thank you sooo much in advance!

**Comment by jaruba** [comment]
Hi, I deployed it again, I still don't know the previous errors that made it go down, but it seems to be working for now, I'll try to monitor it.

**Comment by nyouness** [comment]
Hii again , i think Anilist provider is not working and thank you for keeping this addon alive !

**Comment by jaruba** [comment]
@nyouness hi, what catalogs are not working exactly? it seems that the anilist trending catalog i use does work

**Comment by nyouness** [comment]
yes trending catalog the only one is working but Popular This Season , Upcoming Next Season , All Time Popular , Top Anime are not

**Comment by jaruba** [comment]
i had some time to look into this and pushed a fix, it should work again when the cache expires
